//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4333Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        public string CodClienta { get; set; }
        public string Doljnost { get; set; }
        public string FIO { get; set; }
        public string Loginn { get; set; }
        public string Parol { get; set; }
        public string PosledniVhod { get; set; }
        public string TipVhoda { get; set; }
    }
}
